/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mileset.neeleshengineers.View.laborinvoice;

//import controller.Database.Fetch.getInvoiceCount;
//import controller.Database.INsert.SaveInvoice;
//import controller.Database.INsert.SaveInvoiceItems;
//import controller.Database.INsert.SaveInvoiceMaster;
import com.mileset.neeleshengineers.View.Invoice.ShowAllInvoicesByPoid1;
import com.mileset.neeleshengineers.View.Invoice.ShowwAllInvoicesByPoid1Vars;
import com.mileset.neeleshengineers.View.PurchaseOrder.ShowAllPurchaseOrder;
import com.mileset.neeleshengineers.View.PurchaseOrder.ShowAllPurchaseOrderVars;
import com.mileset.neeleshengineers.View.Report.LabourInvoice;
import com.mileset.neeleshengineers.modal.Customer;
import com.mileset.neeleshengineers.modal.Invoice.Invoice_details;
import com.mileset.neeleshengineers.modal.Invoice.Items;
import com.mileset.neeleshengineers.modal.laborinvoice.LaborInvoiceDetails;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import com.mileset.neeleshengineers.modal.laborinvoice.LaborInvoiceItems;
import com.mileset.neeleshengineers.util.FirebaseMethods;
import com.mileset.neeleshengineers.util.NumberToWord;
import com.mileset.neeleshengineers.util.UtilVars;
import com.mileset.neeleshengineers.util.Utility;
import java.awt.Font;
import java.util.Date;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import modal.operations.NumberToWordsConverter;

/**
 *
 * @author Rahul
 */
public class NewLaborInvoice extends javax.swing.JDialog {

    /**
     * Creates new form NewInvoice1
     */
    private boolean isNewLaborInvocie;

    public NewLaborInvoice(String invoice_id) {
        initComponents();
        jTable1.setFont(new Font("Serif", Font.PLAIN, 20));
        this.setAlwaysOnTop(true);

        this.setTitle(UtilVars.getCustomer().getName() + ", " + UtilVars.getCustomer().getAddress());
        lbl_invoiceid.setText(invoice_id);
        Invoice_details invoice = UtilVars.getRequiredInvoiceDetails();
        lbl_total.setText(Double.toString(invoice.getBasicTotal()));
        //lblCgst.setText(Double.toString(invoice.getCgst()));
        txt_billdate.setText(invoice.getDate());
        lbl_deliverydate.setText(invoice.getDate());
        lbl_total.setText(Double.toString(invoice.getBasicTotal()));
        txt_othercharges.setText(Double.toString(invoice.getOthercharges()));
        txt_cgst.setText(Double.toString(invoice.getCgst()));
        txt_sgst.setText(Double.toString(invoice.getSgst()));
        txt_igst.setText(Double.toString(invoice.getIgst()));
        lbl_grandtotal.setText(Double.toString(invoice.getGrandTotal()));
        Double d = invoice.getGrandTotal();
        lbl_inwords.setText(NumberToWord.NumberToWord(d.intValue() + ""));
        txt_pono.setText(invoice.getPONo());
        txt_date.setText(invoice.getDte2());
        txt_vendorcode.setText(UtilVars.getCustomer().getVendor_code());
        setToTable(invoice.getItemList());
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {

                ShowAllInvoicesByPoid1 sap = new ShowAllInvoicesByPoid1(ShowwAllInvoicesByPoid1Vars.getInvoices(), ShowwAllInvoicesByPoid1Vars.getCustomer());
                sap.setVisible(true);
            }

        });

    }

    private void setToTable(ArrayList<Items> items) {
        //      data = firebaseMethods.getAllCustomers();
        System.out.println("setToTable called");
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
        }

        for (Items i : items) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Vector row = new Vector();
            row.add(i.getItem_name());
            row.add(i.getHsn());
            row.add(i.getQuantity());
            row.add(i.getUnit_rate());
            row.add(i.getAmount());
            row.add(i.getItemCode());
            row.add(i.getDrawingNumber());
            row.add(i.getUnitCode());
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JTextField();
        txt_cgst = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_igst = new javax.swing.JTextField();
        txt_othercharges = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_inwords = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_grandtotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_vendorcode = new javax.swing.JTextField();
        txt_pono = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        txt_vehicleno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbl_invoiceid = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_billdate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lbl_deliverydate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtChallanNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtChallanDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Labour Invoice");
        setModal(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "hsn", "Quantity", "Unit Rate", "Total", "Item Code", "Drawing Number", "Unit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setText("CGST");

        txt_sgst.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_sgst.setText("jTextField6");
        txt_sgst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_sgstFocusLost(evt);
            }
        });
        txt_sgst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_sgstKeyReleased(evt);
            }
        });

        txt_cgst.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_cgst.setText("jTextField5");
        txt_cgst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cgstFocusLost(evt);
            }
        });
        txt_cgst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cgstKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setText("SGST");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setText("IGST");

        txt_igst.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_igst.setText("jTextField7");
        txt_igst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_igstFocusLost(evt);
            }
        });
        txt_igst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_igstKeyReleased(evt);
            }
        });

        txt_othercharges.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_othercharges.setText("jTextField8");
        txt_othercharges.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_otherchargesKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel14.setText("Freight Charges");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setText("Total");

        lbl_total.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lbl_total.setText("basic total");
        lbl_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_totalMouseReleased(evt);
            }
        });

        lbl_inwords.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lbl_inwords.setText("jLabel18");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel17.setText("In Words");

        lbl_grandtotal.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lbl_grandtotal.setText("jLabel16");
        lbl_grandtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_grandtotalMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setText("Grand Total");

        btn_save.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel20.setText("Vendor Code");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel21.setText("P.O. No.");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel22.setText("P.O Date");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel23.setText("Vehicle No");

        txt_vendorcode.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_vendorcode.setText("jTextField11");

        txt_pono.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_pono.setText("jTextField12");

        txt_date.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_date.setText("jTextField13");

        txt_vehicleno.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_othercharges, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txt_cgst)
                            .addComponent(txt_sgst)
                            .addComponent(txt_igst))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_pono)
                                            .addComponent(txt_date)
                                            .addComponent(txt_vehicleno)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_vendorcode, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(20, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_grandtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btn_save)
                        .addContainerGap(111, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_inwords, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lbl_total))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_othercharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cgst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_sgst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_igst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lbl_grandtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_save))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_vendorcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txt_pono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt_vehicleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_inwords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setText("Invoice Id");

        lbl_invoiceid.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lbl_invoiceid.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setText("Bill Date");

        txt_billdate.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_billdate.setText("jTextField9");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel13.setText("For Eg: 25/3/1992");

        lbl_deliverydate.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lbl_deliverydate.setText("Delivery Date");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setText("Challan No.");

        txtChallanNo.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setText("Challan Date");

        txtChallanDate.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_invoiceid, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChallanNo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_billdate, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtChallanDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_deliverydate, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_invoiceid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(txt_billdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_deliverydate))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtChallanNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(txtChallanDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sgstKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sgstKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sgstKeyReleased

    private void txt_cgstKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cgstKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cgstKeyReleased

    private void txt_igstKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_igstKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_igstKeyReleased

    private void txt_otherchargesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_otherchargesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otherchargesKeyReleased

    private void lbl_totalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_totalMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_totalMouseReleased

    private void lbl_grandtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_grandtotalMouseClicked
    }//GEN-LAST:event_lbl_grandtotalMouseClicked

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String invoice_id = lbl_invoiceid.getText();
        String dte = txt_billdate.getText();
        String challanNo = txtChallanNo.getText();
        double other = Double.parseDouble(txt_othercharges.getText());
        double cgst = Double.parseDouble(txt_cgst.getText());
        double sgst = Double.parseDouble(txt_sgst.getText());
        double igst = Double.parseDouble(txt_igst.getText());
        double grand = Double.parseDouble(lbl_grandtotal.getText());;
        double basic = Double.valueOf(lbl_total.getText().toString());
        String vendorCode = txt_vendorcode.getText().trim();
        String pono = txt_pono.getText().trim();
        String dte2 = txt_date.getText().trim();
        String vehicleNo = txt_vehicleno.getText().trim();
        ArrayList<LaborInvoiceItems> invoiceItems = getJTableData();

        LaborInvoiceDetails invoice_details = new LaborInvoiceDetails();
        invoice_details.setBasicTotal(basic);
        invoice_details.setCgst(cgst);
        invoice_details.setDate(dte);
        invoice_details.setDte2(dte2);
        invoice_details.setGrandTotal(grand);
        invoice_details.setIgst(igst);
        invoice_details.setInvoice_id(invoice_id);
        invoice_details.setItemList(invoiceItems);
        invoice_details.setOthercharges(other);
        invoice_details.setPONo(pono);
        invoice_details.setSgst(sgst);
        invoice_details.setVehicleNo(vehicleNo);
        invoice_details.setVendorCode(vendorCode);
        invoice_details.setChallanNo(challanNo);
        invoice_details.setChallanDate(txtChallanDate.getText());
        invoice_details.setCname(UtilVars.getCustomer().getName() + "\n" + UtilVars.getCustomer().getAddress());
        String dDate = UtilVars.getPo().getDelivery_date();
        String bDate = txt_billdate.getText().toString();
        Date dd = Utility.convertStringToDate(dDate);
        Date bd = Utility.convertStringToDate(bDate);
        if (bd.after(dd)) {
            JOptionPane.showMessageDialog(this, "Bill date should be less than Delivery Date");
            return;
        }
        LabourInvoice labour = new LabourInvoice(invoice_details);
        this.dispose();
        FirebaseMethods.addNewLaborInvoice(invoice_details, this);
    }//GEN-LAST:event_btn_saveActionPerformed

    private ArrayList<LaborInvoiceItems> getJTableData() {
        System.out.println("getJTableData Called");
        ArrayList<LaborInvoiceItems> items = new ArrayList();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (model != null) {
            for (int count = 0; count < model.getRowCount(); count++) {
                //numdata.add();
                String item_name = model.getValueAt(count, 0).toString();
                String hsn = model.getValueAt(count, 1).toString();
                int quantity = Integer.valueOf(model.getValueAt(count, 2).toString());
                Double unit_rate = Double.valueOf(model.getValueAt(count, 3).toString());
                Double total = Double.valueOf(model.getValueAt(count, 4).toString());
                String itemCode = model.getValueAt(count, 5).toString();
                String drawingNumber = model.getValueAt(count, 6).toString();
                String unitCode = model.getValueAt(count, 7).toString();
                LaborInvoiceItems item = new LaborInvoiceItems();
                item.setItemCode(itemCode);
                item.setDrawingNumber(drawingNumber);
                item.setAmount(total);
                //item.setHSN(hsn);
                item.setItem_name(item_name);
                item.setQuantity(quantity);
                item.setUnit_rate(unit_rate);
                item.setUnitCode(unitCode);
                items.add(item);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please add items first");
        }
        System.out.println(items);
        return items;
    }
    private void txt_cgstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cgstFocusLost
    }//GEN-LAST:event_txt_cgstFocusLost

    private void txt_sgstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sgstFocusLost
    }//GEN-LAST:event_txt_sgstFocusLost

    private void txt_igstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_igstFocusLost
    }//GEN-LAST:event_txt_igstFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLaborInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLaborInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLaborInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLaborInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_deliverydate;
    private javax.swing.JLabel lbl_grandtotal;
    private javax.swing.JLabel lbl_invoiceid;
    private javax.swing.JLabel lbl_inwords;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField txtChallanDate;
    private javax.swing.JTextField txtChallanNo;
    private javax.swing.JTextField txt_billdate;
    private javax.swing.JTextField txt_cgst;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_igst;
    private javax.swing.JTextField txt_othercharges;
    private javax.swing.JTextField txt_pono;
    private javax.swing.JTextField txt_sgst;
    private javax.swing.JTextField txt_vehicleno;
    private javax.swing.JTextField txt_vendorcode;
    // End of variables declaration//GEN-END:variables

}
