/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mileset.neeleshengineers.View.laborinvoice;

import com.mileset.neeleshengineers.View.Invoice.*;
import com.mileset.neeleshengineers.View.PurchaseOrder.PurchaseOrder;
import com.mileset.neeleshengineers.View.PurchaseOrder.PurchaseOrderVars;
import com.mileset.neeleshengineers.View.PurchaseOrder.ShowAllPurchaseOrder;
import com.mileset.neeleshengineers.View.PurchaseOrder.ShowAllPurchaseOrderVars;
import com.mileset.neeleshengineers.View.Report.LabourInvoice;
import com.mileset.neeleshengineers.modal.Customer;
import com.mileset.neeleshengineers.modal.Invoice.Invoice_details;
import com.mileset.neeleshengineers.modal.Po;
import com.mileset.neeleshengineers.modal.laborinvoice.LaborInvoiceDetails;
import com.mileset.neeleshengineers.util.FirebaseMethods;
import com.mileset.neeleshengineers.util.UtilVars;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rahul
 */
public class ShowAllLaborInvoicesByPoid1 extends javax.swing.JDialog {

    /**
     * Creates new form ShowAllInvoicesByPoid1
     */
    ArrayList<LaborInvoiceDetails> invoices;

    public ShowAllLaborInvoicesByPoid1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTable1.setFont(new Font("Serif", Font.PLAIN, 14));

    }

    public ShowAllLaborInvoicesByPoid1(final ArrayList<LaborInvoiceDetails> invoices) {
        initComponents();
        jTable1.setFont(new Font("Serif", Font.PLAIN, 14));
        this.invoices = invoices;
        loadInvoiceToJTable(invoices);
        jLabel2.setText(UtilVars.getCustomer().getName());
        jTable1.setRowSelectionAllowed(true);

        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jLabel1.setText(jLabel1.getText() + " " + invoices.get(0).getPONo());
        this.setTitle("Labour Invoices for " + jLabel1.getText());
        jTable1.setCellSelectionEnabled(false);
        jTable1.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();
                Point point = mouseEvent.getPoint();
                int row = table.rowAtPoint(point);
                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    LaborInvoiceDetails invoice_details = getSelectedInvoice(invoices);
                    System.out.println(invoice_details);
                }
            }
        });
    }

    private LaborInvoiceDetails getSelectedInvoice(ArrayList<LaborInvoiceDetails> invoices) {
        LaborInvoiceDetails invoice_details = new LaborInvoiceDetails();
        String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        for (LaborInvoiceDetails invoice_detail : invoices) {
            if (invoice_detail.getInvoice_id().equalsIgnoreCase(id)) {
                invoice_details = invoice_detail;
                break;
            }
        }
        return invoice_details;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_updateLaborInvoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice id", "Po No", "Date", "Items", "basic total", "Grand total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Purchase Order No:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Customer Name:");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Save To Pdf");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_updateLaborInvoice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_updateLaborInvoice.setText("Update Labor Invoice");
        btn_updateLaborInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateLaborInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_updateLaborInvoice)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_updateLaborInvoice))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getSelectedId() {
        String val = "";
        try {
            int row = jTable1.getSelectedRow();

            val = jTable1.getValueAt(row, 0) + "";

        } catch (IndexOutOfBoundsException ex) {
            //ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Please select id to update");
        }
        return val;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LaborInvoiceDetails invoice_details = getSelectedInvoice(invoices);
        LabourInvoice labour = new LabourInvoice(invoice_details);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_updateLaborInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateLaborInvoiceActionPerformed
        final String poid = getSelectedId();
        final JDialog thisdialog = this;
        Thread worker = new Thread() {
            public void run() {
                try {
                    try {
                        if (!poid.equals("")) {
                            for (LaborInvoiceDetails lbd : invoices) {
                                if (lbd.getInvoice_id().equalsIgnoreCase(poid)) {
                                    com.mileset.neeleshengineers.View.newlaborinvoice.NewLabourInvoice nli = new com.mileset.neeleshengineers.View.newlaborinvoice.NewLabourInvoice(lbd);
                                    nli.setVisible(true);
                                    thisdialog.dispose();
                                }
                            }
                        }

                    } catch (NullPointerException ex) {
                        JOptionPane.showMessageDialog(thisdialog, "Please select id.");
                        ex.printStackTrace();
                    }

                } catch (Exception ex) {
                    System.out.println("Exception occured " + ex);
                }
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {

                    }
                });
            }
        };
        worker.start();

    }//GEN-LAST:event_btn_updateLaborInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShowAllLaborInvoicesByPoid1 dialog = new ShowAllLaborInvoicesByPoid1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void loadInvoiceToJTable(ArrayList<LaborInvoiceDetails> data1) {
        System.out.println("setToTable called");
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
        }

        System.out.println("row:" + data1.size());
        for (int i = 0; i < data1.size(); i++) {
            //  DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Vector row = new Vector();
            row.add(data1.get(i).getInvoice_id());
            row.add(data1.get(i).getPONo());
            row.add(data1.get(i).getDate());
            row.add(data1.get(i).getItemList().size());
            row.add(data1.get(i).getBasicTotal());
            row.add(data1.get(i).getGrandTotal());
            //model.addRow(row);
            //dm.addRow(row);
            dm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_updateLaborInvoice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
